# Welcome to Nubia Jekyll Theme!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

theme_version: 1.0.4

# Site settings
title:              Riebeckstraße 63
logo:               /images/pages/head.png
description:        Der Initiativkreis Riebeckstraße 63 hat sich am 3. Juli 2019 am historischen Ort der ehemaligen städtischen Arbeitsanstalt gegründet. Das Bündnis aus über 30 Einzelpersonen, zivilgesellschaftlichen, städtischen und wissenschaftlichen Akteuren setzt sich für die Gestaltung eines lebendigen Erinnerungsortes ein. Zentral ist unsere Forderung nach einem Gedenken und Lernen am authentischen Ort – betreibt der heutige Träger des Geländes, der Städtische Eigenbetrieb Behindertenhilfe (SEB) hier zurzeit noch eine Gemeinschaftsunterkunft für Geflüchtete und ein Wohnprojekt für Kinder und Jugendliche, werden Gebäudeteile in Zukunft zur Disposition stehen.
baseurl:            '' # The subpath of your site, e.g. /blog
url:                'https://riebeckstrasse63.de' # The base hostname & protocol for your site
#twitter:            https://twitter.com/aspirethemes
facebook:           https://www.facebook.com/riebeckstrasse63/
#instagram:          https://www.instagram.com/aspirethemes

markdown:  kramdown
permalink: pretty
paginate:  11
sass:
  style: compressed

gems:
  - jekyll-paginate
  - jekyll/tagging

include:
  - _pages

exclude:
  - vendor
  - Gemfile
  - Gemfile.lock

# Tags
tag_page_dir:         tag
tag_page_layout:      tag_page
tag_permalink_style:  pretty

# Pages path
defaults:
  - scope:
      path: '_pages'
    values:
      permalink: /:basename:output_ext

# Authors
authors:
  ahmad:
    name:     Ahmad Ajmi
    bio:      Author & developer of Aspire Themes. Minimalist. I love creating clean and minimal websites.Technical writer at SitePoint.
    gravatar: https://s.gravatar.com/avatar/f83141edd9e6339e678648596a403fd5?s=150
    email:    info@aspirethemes.com
    website:  http://aspirethemes.com
    github:   https://github.com/aspirethemes
    twitter:  https://twitter.com/aspirethemes
